{
  "openapi": "3.0.0",
  "info": {
    "description": "**Introduction**\n\nThis API provides the ability to retrieve and manage certain elements within the iPilot system. \n\n**OpenAPI Specification**\n\nThis API is documented in **OpenAPI format**.\n\n**Authentication**\n\niPilot requires two authentication elements:\n  - User credentials\n  - and an API Key\n\n\nTo request an API Key please email a request for an iPilot API Key to [support@nuwave.com](support@nuwave.com)\n\nOnce you have received your API Key you will then have[...]",
    "version": "v1.7",
    "title": "iPilot Management API",
    "x-logo": {
      "url": "https://24204443.fs1.hubspotusercontent-na1.net/hub/24204443/hubfs/Ipilot_July2023/Images/iPILOT_logo.png",
      "backgroundColor": "#FFFFFF",
      "altText": "iPilot Management API"
    }
  },
  "servers": [
    {
      "url": "https://api.nuwave.com/v1",
      "variables": {
        "basePath": {
          "default": "/v1"
        }
      }
    }
  ],
  "tags": [
    {
      "name": "Authorization",
      "description": "This section provides details on authenticating and getting the access token needed for subsequent API calls."
    },
    {
      "name": "Accounts",
      "description": "This section provides the ability to manage Accounts in the iPilot system. You can retrieve, create, update and delete accounts through this section. This is where you will be able to manage Vendor, Customer and User account types."
    },
    {
      "name": "Call Forwarding",
      "description": "This section provides the ability to manage call forwarding for your phone numbers."
    },
    {
      "name": "Calling Party Number",
      "description": "This section provides the ability to manage calling party number (CPN) for your phone numbers."
    },
    {
      "name": "Carrier Management",
      "description": "This section provides the ability to access Carrier Management funcionality, getting carriers available, uploading numbers to a carrier, removing numbers."
    },
    {
      "name": "CNAM",
      "description": "This section provides the ability to manage outbound CNAM for your phone numbers."
    },
    {
      "name": "Disaster Plans",
      "description": "This section provides the ability to manage your disaster plans for your phone numbers."
    },
    {
      "name": "Site Management",
      "description": "This section provides the ability to manage sites inside of iPilot, retrieving, adding, removing, users in sites."
    },
    {
      "name": "Emergency Addresses",
      "description": "This section provides the ability manage Emeregency Services addresses, retrieving, updating, adding and/or removing."
    },
    {
      "name": "International Calling",
      "description": "This section provides the ability to manage international calling for your phone numbers."
    },
    {
      "name": "Microsoft Teams",
      "description": "This section provides the ability to manage the Microsoft Teams functionality in the iPilot system. You have the ability to retrieve numbers available for provisioining, provisioning a user to a phone number, retrieving user detailed information, updating user detailed information etc."
    },
    {
      "name": "Zoom",
      "description": "This section provides the ability to manage the Zoom peering exchange phone numbers in the iPilot system. You have the ability to retrieve numbers available for provisioining, provisioning a user to a phone number, retrieving user detailed information, updating user detailed information etc."
    }
  ],
  "paths": {
    "/oauth2/authorize": {
      "post": {
        "summary": "Get authentication token",
        "tags": [
          "Authorization"
        ],
        "security": [
          {
            "api_key": []
          }
        ]
      }
    },
    "/accounts": {
      "get": {
        "summary": "Get current account details",
        "tags": [
          "Accounts"
        ],
        "description": "Retrieves the current logged in account details",
        "security": [
          {
            "x-access-token": [
              "write:Accounts",
              "read:Accounts"
            ]
          }
        ]
      }
    },
    "/accounts/customers": {
      "get": {
        "summary": "Get list of customers under current account login",
        "tags": [
          "Accounts"
        ],
        "description": "Retrieves the list of customers based on the current logged in account (Reseller, Admin etc.)",
        "security": [
          {
            "x-access-token": [
              "write:Accounts",
              "read:Accounts"
            ]
          }
        ]
      }
    },
    "/accounts/resellers": {
      "get": {
        "summary": "Get list of resellers under current account login",
        "tags": [
          "Accounts"
        ],
        "description": "Retrieves the list of resellers based on the current logged in account (Reseller, Admin etc.)",
        "security": [
          {
            "x-access-token": [
              "write:Accounts",
              "read:Accounts"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create a new account",
        "tags": [
          "Accounts"
        ],
        "description": "Creates a new account",
        "security": [
          {
            "x-access-token": [
              "write:Accounts",
              "read:Accounts"
            ]
          }
        ]
      }
    },
    "/accounts/{id}": {
      "delete": {
        "summary": "Delete or deactivate an account",
        "tags": [
          "Accounts"
        ],
        "description": "Deletes an iPilot account.  Note that all numbers must already be deprovisioned and deleted before delete will succeed",
        "security": [
          {
            "x-access-token": [
              "write:Accounts",
              "read:Accounts"
            ]
          }
        ]
      },
      "get": {
        "summary": "Get Account details",
        "tags": [
          "Accounts"
        ],
        "description": "Returns back account details",
        "security": [
          {
            "x-access-token": [
              "write:Accounts",
              "read:Accounts"
            ]
          }
        ]
      },
      "put": {
        "summary": "Update account details",
        "tags": [
          "Accounts"
        ],
        "description": "Update account details",
        "security": [
          {
            "x-access-token": [
              "write:Accounts",
              "read:Accounts"
            ]
          }
        ]
      }
    },
    "/callForwarding/{customerId}": {
      "post": {
        "summary": "Add call forwarding for phone number(s)",
        "tags": [
          "Call Forwarding"
        ],
        "description": "Add call forwarding for phone number(s)",
        "security": [
          {
            "x-access-token": [
              "write:CallForwarding",
              "read:CallForwarding"
            ]
          }
        ]
      },
      "put": {
        "summary": "Update call forwarding",
        "tags": [
          "Call Forwarding"
        ],
        "description": "Update call forwarding",
        "security": [
          {
            "x-access-token": [
              "write:CallForwarding",
              "read:CallForwarding"
            ]
          }
        ]
      }
    },
    "/callForwarding/{customerId}/{phoneNumber}": {
      "get": {
        "summary": "Retrieve call forwarding details",
        "tags": [
          "Call Forwarding"
        ],
        "description": "Retrieve call forwarding details",
        "security": [
          {
            "x-access-token": [
              "write:CallForwarding",
              "read:CallForwarding"
            ]
          }
        ]
      }
    },
    "/callForwarding/{id}": {
      "delete": {
        "summary": "Remove call forwarding from telephone number",
        "tags": [
          "Call Forwarding"
        ],
        "description": "Remove call forwarding from telephone number",
        "security": [
          {
            "x-access-token": [
              "write:CallForwarding"
            ]
          }
        ]
      }
    },
    "/callingPartyNumber/{customerId}": {
      "post": {
        "summary": "Add calling party number for phone number(s)",
        "tags": [
          "Calling Party Number"
        ],
        "description": "Add calling party number for phone number(s)",
        "security": [
          {
            "x-access-token": [
              "write:CallingPartyNumber",
              "read:CallingPartyNumber"
            ]
          }
        ]
      }
    },
    "/callingPartyNumber/{phoneNumber}": {
      "get": {
        "summary": "Retrieve calling party number details",
        "tags": [
          "Calling Party Number"
        ],
        "description": "Retrieve calling party number details",
        "security": [
          {
            "x-access-token": [
              "write:CallingPartyNumber",
              "read:CallingPartyNumber"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Remove calling party number from telephone number",
        "tags": [
          "Calling Party Number"
        ],
        "description": "Remove calling party number from telephone number",
        "security": [
          {
            "x-access-token": [
              "write:CallingPartyNumber"
            ]
          }
        ]
      }
    },
    "/cnam/{customerId}": {
      "post": {
        "summary": "Add outbound CNAM for phone number(s)",
        "tags": [
          "CNAM"
        ],
        "description": "Add outbound CNAM for phone number(s)",
        "security": [
          {
            "x-access-token": [
              "write:CallingPartyNumber",
              "read:CallingPartyNumber"
            ]
          }
        ]
      }
    },
    "/cnam/{phoneNumber}": {
      "get": {
        "summary": "Retrieve CNAM details",
        "tags": [
          "CNAM"
        ],
        "description": "Retrieve CNAM details",
        "security": [
          {
            "x-access-token": [
              "write:CNAM",
              "read:CNAM"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Remove CNAM from telephone number",
        "tags": [
          "CNAM"
        ],
        "description": "Remove CNAM from telephone number",
        "security": [
          {
            "x-access-token": [
              "write:CNAM"
            ]
          }
        ]
      }
    },
    "/disasterPlan/{customerId}": {
      "post": {
        "summary": "Add disaster plan for phone number(s)",
        "tags": [
          "Disaster Plans"
        ],
        "description": "Add disaster plan for phone number(s)",
        "security": [
          {
            "x-access-token": [
              "write:DisasterPlans",
              "read:DisasterPlans"
            ]
          }
        ]
      },
      "get": {
        "summary": "Retrieve Disaster Plan details",
        "tags": [
          "Disaster Plans"
        ],
        "description": "Retrieve Disaster Plan details",
        "security": [
          {
            "x-access-token": [
              "write:DisasterPlans",
              "read:DisasterPlans"
            ]
          }
        ]
      },
      "put": {
        "summary": "Update disaster plan",
        "tags": [
          "Disaster Plans"
        ],
        "description": "Update disaster plan",
        "security": [
          {
            "x-access-token": [
              "write:DisasterPlans",
              "read:DisasterPlans"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Remove Disaster Plans from telephone number",
        "tags": [
          "Disaster Plans"
        ],
        "description": "Remove Disaster Plans from telephone number",
        "security": [
          {
            "x-access-token": [
              "write:DisasterPlans"
            ]
          }
        ]
      }
    },
    "/msteams/{subdomain}/carriers": {
      "get": {
        "summary": "Retrieve list of carriers",
        "tags": [
          "Carrier Management"
        ],
        "description": "Retrieve list of Carriers",
        "security": [
          {
            "x-access-token": [
              "write:Carriers",
              "read:Carriers"
            ]
          }
        ]
      }
    },
    "/msteams/{subdomain}/carriers/{id}/numbers": {
      "get": {
        "summary": "Get Carrier Numbers",
        "tags": [
          "Carrier Management"
        ],
        "description": "Returns back carrier numbers",
        "security": [
          {
            "x-access-token": [
              "write:Carriers",
              "read:Carriers"
            ]
          }
        ]
      },
      "post": {
        "summary": "Upload phone numbers to carrier",
        "tags": [
          "Carrier Management"
        ],
        "description": "Upload phone numbers to carrier",
        "security": [
          {
            "x-access-token": [
              "write:Carriers",
              "read:Carriers"
            ]
          }
        ]
      }
    },
    "/msteams/{subdomain}/emergency/addresses": {
      "get": {
        "summary": "Get Emergency Addresses",
        "tags": [
          "Emergency Addresses"
        ],
        "description": "Returns back emergency addresses",
        "security": [
          {
            "x-access-token": [
              "read:EmergencyAddresses"
            ]
          }
        ]
      },
      "post": {
        "summary": "Add emergency address to account",
        "tags": [
          "Emergency Addresses"
        ],
        "description": "Add emergency addresses to customer account"
      }
    },
    "/msteams/{subdomain}/emergency/addresses/{id}": {
      "put": {
        "summary": "Update emergency address on account",
        "tags": [
          "Emergency Addresses"
        ],
        "description": "Add emergency addresses to customer account"
      },
      "delete": {
        "summary": "Remove emergency address from account",
        "tags": [
          "Emergency Addresses"
        ],
        "description": "Remove emergency addresses from customer account",
        "security": [
          {
            "x-access-token": [
              "write:EmergencyAddresses"
            ]
          }
        ]
      }
    },
    "/internationalCalling/{customerId}": {
      "post": {
        "summary": "Enable international calling for phone number(s)",
        "tags": [
          "International Calling"
        ],
        "description": "Enable international calling for phone number(s)",
        "security": [
          {
            "x-access-token": [
              "write:InternationalCalling",
              "read:InternationalCalling"
            ]
          }
        ]
      }
    },
    "/internationalCalling/{phoneNumber}": {
      "get": {
        "summary": "Retrieve international calling on phone number",
        "tags": [
          "International Calling"
        ],
        "description": "Retrieve international calling on phone number",
        "security": [
          {
            "x-access-token": [
              "write:InternationalCalling",
              "read:InternationalCalling"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Remove international calling from phone number",
        "tags": [
          "International Calling"
        ],
        "description": "Remove international calling from phone number",
        "security": [
          {
            "x-access-token": [
              "write:InternationalCalling"
            ]
          }
        ]
      }
    },
    "/site": {
      "get": {
        "summary": "Retrieve list of sites",
        "tags": [
          "Site Management"
        ],
        "description": "Retrieve list of sites",
        "security": [
          {
            "x-access-token": [
              "write:Sites",
              "read:Sites"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create a new Site",
        "tags": [
          "Site Management"
        ],
        "description": "Creates a new Site",
        "security": [
          {
            "x-access-token": [
              "write:Sites",
              "read:Sites"
            ]
          }
        ]
      }
    },
    "/site/{id}": {
      "delete": {
        "summary": "Removes a site",
        "tags": [
          "Site Management"
        ],
        "description": "Removes an iPilot site.  Note that all users must already be removed from a site otherwise this command will fail due to users still be assigned to this site.",
        "security": [
          {
            "x-access-token": [
              "write:Sites",
              "read:Sites"
            ]
          }
        ]
      },
      "get": {
        "summary": "Get Site details",
        "tags": [
          "Site Management"
        ],
        "description": "Returns back site details",
        "security": [
          {
            "x-access-token": [
              "write:Sites",
              "read:Sites"
            ]
          }
        ]
      },
      "put": {
        "summary": "Update site details",
        "tags": [
          "Site Management"
        ],
        "description": "Update site details",
        "security": [
          {
            "x-access-token": [
              "write:Sites",
              "read:Sites"
            ]
          }
        ]
      }
    },
    "/msteams": {
      "get": {
        "summary": "Retrieves list of configured iPilot customer identifiers for Microsoft Teams, also known as subdomain.",
        "tags": [
          "Microsoft Teams"
        ],
        "description": "Returns back list of configured customer identifiers the authenticated user has permission to access.",
        "security": [
          {
            "x-access-token": [
              "write:MicrosoftTeams",
              "read:MicrosoftTeams"
            ]
          }
        ]
      }
    },
    "/msteams/{subDomain}/users/{id}": {
      "delete": {
        "summary": "Unprovision a user from a phone number",
        "tags": [
          "Microsoft Teams"
        ],
        "description": "Unprovision user from phone number returning it into pool",
        "security": [
          {
            "x-access-token": [
              "write:MicrosoftTeams",
              "read:MicrosoftTeams"
            ]
          }
        ]
      },
      "get": {
        "summary": "Get detailed user information",
        "tags": [
          "Microsoft Teams"
        ],
        "description": "Returns back a single user detail record",
        "security": [
          {
            "x-access-token": [
              "write:MicrosoftTeams",
              "read:MicrosoftTeams"
            ]
          }
        ]
      },
      "put": {
        "summary": "Update detailed user information",
        "tags": [
          "Microsoft Teams"
        ],
        "description": "Update a single user detail record",
        "security": [
          {
            "x-access-token": [
              "write:MicrosoftTeams",
              "read:MicrosoftTeams"
            ]
          }
        ]
      }
    },
    "/msteams/{subDomain}/users": {
      "get": {
        "summary": "Retreive list of numbers available and provisioned user",
        "tags": [
          "Microsoft Teams"
        ],
        "description": "Return back a list of provisioned users",
        "security": [
          {
            "x-access-token": [
              "write:MicrosoftTeams",
              "read:MicrosoftTeams"
            ]
          }
        ]
      },
      "post": {
        "summary": "Provision a new user UPN to a telephone number",
        "tags": [
          "Microsoft Teams"
        ],
        "description": "Provisions a user to a telephone number",
        "security": [
          {
            "x-access-token": [
              "write:MicrosoftTeams",
              "read:MicrosoftTeams"
            ]
          }
        ]
      }
    },
    "/msteams/{subDomain}/numbers": {
      "get": {
        "summary": "Get numbers that are available in pool",
        "tags": [
          "Microsoft Teams"
        ],
        "description": "Return list of available numbers.  Numbers must be ordered through iPilot portal first",
        "security": [
          {
            "x-access-token": [
              "write:MicrosoftTeams",
              "read:MicrosoftTeams"
            ]
          }
        ]
      }
    },
    "/zoom": {
      "get": {
        "summary": "Retrieves list of Zoom phone number inventory",
        "tags": [
          "Zoom"
        ],
        "description": "Retrieves list of Zoom phone number inventory",
        "security": [
          {
            "x-access-token": [
              "write:Zoom",
              "read:Zoom"
            ]
          }
        ]
      },
      "post": {
        "summary": "Provision/Peer phone number to Zoom Account.",
        "tags": [
          "Zoom"
        ],
        "description": "Provisions/Peers phone number(s) to the linked Zoom Account.",
        "security": [
          {
            "x-access-token": [
              "write:Zoom",
              "read:Zoom"
            ]
          }
        ]
      }
    },
    "/zoom/provisionTo/{id}": {
      "get": {
        "summary": "Get information on provisioned/peered numbers",
        "tags": [
          "Zoom"
        ],
        "description": "Returns back information for provisioned/peered numbers for a customer account in Zoom",
        "security": [
          {
            "x-access-token": [
              "write:MicrosoftTeams",
              "read:MicrosoftTeams"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "x-access-token": {
        "description": "Get access to data while protecting your account credentials.\nOAuth2 is also a safer and more secure way to give you access.\n",
        "type": "oauth2",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://api.nuwave.com/api/v1/oauth2/authorize",
            "scopes": {
              "write:Accounts": "modify accounts in your account",
              "read:Accounts": "read your accounts",
              "write:MicrosoftTeams": "modify Microsoft Teams in your account",
              "read:MicrosoftTeams": "read your Microsoft Teams information"
            }
          }
        }
      },
      "api_key": {
        "type": "apiKey",
        "name": "x-api-key",
        "in": "header"
      }
    }
  }
}